#!/usr/bin/zsh

# this is a simple config for herbstluftwm

hc() {
    herbstclient $@
}

source_if_exists() {
    if [ -f $1 ] ; then
        source $1
    else
        if [ ! -f ~/herbstluftwm.log ] ; then
            touch ~/herbstluftwm.log
        fi
        echo "Unable to locate file: $1 \n" >> ~/herbstluftwm.log
    fi

}

# clear the log
echo "" > ~/herbstluftwm.log

# source the dracula script to comfortably manage colors
source_if_exists ~/.zsh.d/sourced/dracula

# set the wallpaper
nitrogen --set-scaled ~/Pictures/wallpaper

# set the keyboard layout
setxkbmap -layout de -variant nodeadkeys

# keybindings
source_if_exists ~/.hlwm/keybindings

# theme
source_if_exists ~/.hlwm/theme



# tags
#tag_names=( {1..9} )
#tag_keys=( {1..9} 0 )

#hc rename default "${tag_names[0]}" || true
#for i in "${!tag_names[@]}" ; do
#    hc add "${tag_names[$i]}"
#    key="${tag_keys[$i]}"
#    if ! [ -z "$key" ] ; then
#        hc keybind "$Mod-$key" use_index "$i"
#        hc keybind "$Mod-Shift-$key" move_index "$i"
#    fi
#done

# cycle through tags
# hc keybind $Mod-period use_index +1 --skip-visible
# hc keybind $Mod-comma  use_index -1 --skip-visible


# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# set the default frame_layout
hc set default_frame_layout grid
hc keybind $NotMod-v set default_frame_layout vertical
hc keybind $NotMod-h set default_frame_layout horizontal
hc keybind $NotMod-m set default_frame_layout max
hc keybind $NotMod-g set default_frame_layout grid

# do multi monitor setup here, e.g.:
hc set_monitors 1920x1045+0+35 
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done



# launch polybar
killall -q polybar
polybar example & disown
