#!/usr/bin/zsh
#
# this script closes windows or empty frames
# example usage:
# herbstclient spawn path/to/script/better-close
# 
# the same behavior can be achieved with
# herbstclient close_or_remove
#

hc() { herbstclient $@ }

if [ $(hc get_attr tags.focus.curframe_wcount) -eq 0 ] ; then
    hc remove
else 
    hc close
fi

