#!/usr/bin/zsh
#
# this script closes a frame and all windows in it
#

source ~/.config/herbstluftwm/hl-essentials

while [ $(hc get_attr tags.focus.curframe_wcount) -ne 0 ] ; do
    hc close
done

hc remove

