#!/usr/bin/zsh

source ~/.config/herbstluftwm/hl-essentials

# set some variables
Alt=Mod1
Both=Mod1-Mod4
Mod=Mod4

# remove all existing keybinds
hc keyunbind --all

# basic keybinds
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Return spawn rofi -show run
hc keybind $Mod-Shift-Return spawn alacritty
hc keybind $Mod-BackSpace close_or_remove
hc keybind $Mod-r remove
if exists close-all ; then
    hc keybind $Mod-Delete spawn $HL_PATH/close-all
fi
hc keybind $Mod-f fullscreen toggle
if exists change-screen-resolution ; then
    hc keybind $Mod-Shift-f spawn $HL_PATH/change-screen-resolution
fi
hc keybind $Mod-s floating toggle
hc keybind $Mod-Shift-s set_attr clients.focus.floating toggle
hc keybind $Mod-m set_attr clients.focus.minimized true
hc keybind $Mod-Shift-m jumpto last-minimized

# movement
hc keybind $Mod-Left    focus   left
hc keybind $Mod-Down    focus   down
hc keybind $Mod-Up      focus   up
hc keybind $Mod-Right   focus   right

# moving windows
hc keybind $Mod-Shift-Left  shift   left
hc keybind $Mod-Shift-Down  shift   down
hc keybind $Mod-Shift-Up    shift   up
hc keybind $Mod-Shift-Right shift   right

# splitting frames
hc keybind $Both-Left           split   left    0.5
hc keybind $Both-Down           split   bottom  0.5
hc keybind $Both-Up             split   top     0.5
hc keybind $Both-Right          split   right   0.5

hc keybind $Both-Shift-Left     split   left    0.7
hc keybind $Both-Shift-Down     split   bottom  0.3
hc keybind $Both-Shift-Up       split   top     0.3
hc keybind $Both-Shift-Right    split   right   0.7

hc keybind $Both-Control-Left   split   left    0.3
hc keybind $Both-Control-Down   split   bottom  0.7
hc keybind $Both-Control-Up     split   top     0.7
hc keybind $Both-Control-Right  split   right   0.3

hc keybind $Both-space split explode

# resizing frames
step=0.02
hc keybind $Mod-Control-Left        resize  left    +$step
hc keybind $Mod-Control-Down        resize  down    +$step
hc keybind $Mod-Control-Up          resize  up      +$step
hc keybind $Mod-Control-Right       resize  right   +$step

hc keybind $Mod-Control-Shift-Left  resize  left    -$step
hc keybind $Mod-Control-Shift-Down  resize  down    -$step
hc keybind $Mod-Control-Shift-Up    resize  up      -$step
hc keybind $Mod-Control-Shift-Right resize  right   -$step

# changing window placement
hc keybind $Mod-Control-v   set_layout  vertical
hc keybind $Mod-Control-h   set_layout  horizontal
hc keybind $Mod-Control-m   set_layout  max
hc keybind $Mod-Control-g   set_layout  grid
hc keybind $Mod-Control-Tab         cycle_layout
hc keybind $Mod-Control-Shift-Tab   cycle_layout -1

# cycle through stuff
hc keybind $Mod-Tab         cycle
hc keybind $Mod-Shift-Tab   cycle -1
hc keybind $Alt-Tab         cycle_all
hc keybind $Alt-Shift-Tab   cycle_all -1

# mouse
hc mouseunbind --all
hc mousebind $Mod-B1 move
hc mousebind $Mod-B2 zoom
hc mousebind $Mod-B3 resize

