#!/usr/bin/zsh

hc set frame_border_color $(edracula magenta)
hc set frame_border_active_color $(edracula cyan)
hc set frame_border_normal_color $(edracula magenta)
hc set frame_border_width 3
hc set frame_gap 4
hc set frame_bg_transparent true
hc set always_show_frame true
hc set window_gap 2

hc attr theme.reset 1

hc attr theme.inner_color $(edracula yellow)
hc attr theme.inner_width 1
hc attr theme.active.inner_width 3

padding=3
hc attr theme.padding_bottom $padding
hc attr theme.padding_left $padding
hc attr theme.padding_right $padding
hc attr theme.padding_top $padding

